# Generated by Django 5.2.1 on 2025-06-02 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=1000)),
                ('long_live_access_token', models.CharField(max_length=1000)),
                ('refresh_token', models.CharField(max_length=1000)),
                ('token_expires_on', models.DateTimeField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('requires_auth', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Linkedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=1000)),
                ('long_live_access_token', models.CharField(max_length=1000)),
                ('refresh_token', models.CharField(max_length=1000)),
                ('token_expires_on', models.DateTimeField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('requires_auth', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('TEXT', 'text'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('ARTICLE', 'article')], default='text', max_length=20)),
                ('post_status', models.CharField(choices=[('PENDING', 'pending'), ('STARTED', 'started'), ('PROCESSED', 'processed'), ('POSTED', 'posted'), ('ERROR', 'error')], default='pending')),
                ('is_posted', models.BooleanField(default=False)),
                ('error_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('platform_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TikTok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1000)),
                ('long_live_access_token', models.CharField(max_length=1000)),
                ('refresh_token', models.CharField(max_length=1000)),
                ('token_expires_on', models.DateTimeField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('requires_auth', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('x_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tiktok_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=1000)),
                ('long_live_access_token', models.CharField(max_length=1000)),
                ('refresh_token', models.CharField(max_length=1000)),
                ('token_expires_on', models.DateTimeField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('requires_auth', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
