# Generated by Django 5.2.1 on 2025-06-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='refresh_token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedin',
            name='refresh_token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktok',
            name='refresh_token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='x',
            name='refresh_token_expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='long_live_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='long_live_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='long_live_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='x',
            name='long_live_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
