# Generated by Django 5.2.1 on 2025-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_alter_instagram_token_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktok',
            name='token_expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
