"""
Django settings for digitalplatform project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hgpo(k)^4cr4b)!ad42*v+s6(un@o!#=p%rw_8sz=2-vq0dnux"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_celery_beat",
    "socialmedia",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "digitalplatform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "digitalplatform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LINKEDIN_CLIENT_ID = config("LINKEDIN_CLIENT_ID")
LINKEDIN_CLIENT_SECRET = config("LINKEDIN_CLIENT_SECRET")
LINKEDIN_REDIRECT_URL = ""
LINKEDIN_BASE_URL = "https://www.linkedin.com/"
LINKEDIN_API_URL = "https://api.linkedin.com/"

TIKTOK_CLIENT_ID = config("TIKTOK_CLIENT_ID")
TIKTOK_CLIENT_SECRET = config("TIKTOK_CLIENT_SECRET")
TIKTOK_BASE_URL = "https://www.tiktok.com/v2/"
TIKTOK_API_URL = "https://open.tiktokapis.com/v2/"
TIKTOK_REDIRECT_URL = ""

X_CONSUMER_ID = config("X_CONSUMER_ID")
X_CONSUMER_SECRET = config("X_CONSUMER_SECRET")
X_BASE_URL = "https://www.x.com/"
X_API_URL = "https://api.x.com/"
TWITTER_BASED_API_URL = "https://api.twitter.com/"
X_UPLOAD_URL = "https://upload.x.com/"
X_REDIRECT_URL = "https://73a2-129-208-125-202.ngrok-free.app/x_success"

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
# CELERY_BEAT_SCHEDULE = {
#     'check_linkedin_tokens': {
#         'task': 'socialmedia.tasks.check_linkedin_tokens',
#         'schedule': crontab(minute='*/30'),  # Every 30 minutes
#     },
#     'check_tiktok_tokens': {
#         'task': 'socialmedia.tasks.check_tiktok_tokens',
#         'schedule': crontab(minute='*/30'),  # Every 30 minutes
#     },
#     'check_x_tokens': {
#         'task': 'socialmedia.tasks.check_x_tokens',
#         'schedule': crontab(minute='*/30'),  # Every 30 minutes
#     },
# }
CELERY_BEAT_SCHEDULE = {
    "sample_task": {
        "task": "socialmedia.tasks.sample_task",
        "schedule": crontab(minute="*/1"),
    },
}
